#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/uitranscriber/pyenv-3.13.9/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAIRlWElm'
    b'TU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAAB'
    b'AAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAE'
    b'AAAAAQAAACCgAwAEAAAAAQAAACAAAAAAX7wP8AAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlp'
    b'VFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6'
    b'bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRm'
    b'PSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAg'
    b'PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0i'
    b'aHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRh'
    b'dGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAg'
    b'PC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KGV7hBwAAAYhJREFUWAntVrFOwzAQvXOKUJGQ2Dsh'
    b'MfEVjGWhG9/ADyC+AfEnTChI7cpXMCF16s6AqESUHu+sWHLi2G2yIewOtc937+5eotwjyuu/'
    b'M8BJAp6loPc3pssrSfrFLl3sLdcxl7hdJF1cPDK8SWBNQm9YNIBZLp42ix3znAS/MQsohmX1'
    b'wVw6zC5M2KXSDso0OR2fvnAxQazmD127YO2zoAcmqSuqt1+L9cOspAbb9wsZ0OeGpZ0XSF5/'
    b'f25hOPKDDt3viKri5GyKQq4RU9r3qRMcFuBeONCunWty9B/6dYD6jtqJZQ9E2HuH7Tkbb9+z'
    b'tWT02IeY0hh7ChiSaJxvLiAzkBnIDGQG9jAwTga0P8ppjHDKNeMYYxBTlElHanqctNP5J6Su'
    b'DBsIikZMOGzPKSygGZmqZCAm7nSejxUkmlzqHxI2S5uzZxz3N9dIsvPHzY0VE26ee5UftEXn'
    b'wrJc389eY5IsjpMQkvGgyE0CK3wEDgOi1Go4J62dfci/i+UxsnxIouz7lxn4BVfFgJd/nPKR'
    b'AAAAAElFTkSuQmCC')

